# MAGIC Build Pipeline

## Rational

https://github.com/magic-clojure/magic[The original repository] does not work on mac. This pipeline works on mac.

The build pipeline for the https://github.com/nasser/magic[Morgan And Grand Iron Clojure] compiler.

This repository aims to simplify ongoing work on MAGIC by providing a single place to reproducibly build the compiler, its dependencies, and dependents.

## Sub-projects

MAGIC is a complex project consisting of multiple sub-projects hosted in their own repositories with their own histories

### Clojure.Runtime

The data structures, reader, and utility functions Clojure uses at runtime. This does not include the Clojure standard library itself, just the functionality that the standard library uses, such as the implementation of Keywords, Vars, all the persistent data structures, and so on.

It is a C# codebase and can be built with the `dotnet` command line tool.

It is forked from https://github.com/arcadia-unity/clojure-clr[arcadia-unity/clojure-clr] which was forked from the original https://github.com/clojure/clojure-clr[clojure/clojure-clr]. As a result Clojure.Runtime is largely the result of https://github.com/dmiller[David Miller]'s hard work. MAGIC's Clojure.Runtime is a subset of ClojureCLR, removing the C# implementation of the ClojureCLR compiler and making other changes to better work with MAGIC, particularly around how namespaces and files are loaded.

### Magic.Runtime

Additional data structures and utility functionality used by MAGIC. Its primary contribution is to provide the implementation of fast dynamic call sites.

It is a C# codebase and can be built with the `dotnet` command line tool.

The decision was made not to add new functionality to Clojure.Runtime to make ingesting upstream updates easier, so anything "new" that MAGIC needs tends to end up in this runtime instead.

### MAGIC

The MAGIC compiler itself, a pure Clojure transformation of s-expressions to MSIL bytecode. 

This repository also includes a patched Clojure standard library. It is modified for performance and to work with MAGIC's different semantics around type hints. It also provides more flexible mechanisms around file and namespace loading to accommodate MAGIC's self-hosting and running on restrictive platforms like iOS. The modifications are designed to work with Clojure.Runtime.

MAGIC is a pure Clojure codebase and must be built with Nostrand. It depends on https://github.com/nasser/mage[nasser/mage] and https://github.com/clojure/tools.analyzer[clojure/tools.analyzer] which are pulled in by Nostrand during the build.

### Nostrand

A task runner, dependency manager and REPL for Clojure on Mono. Something like Leiningen for MAGIC and the C# runtime.

It is a hybrid C# and Clojure codebase. Its Clojure parts run through MAGIC, so any change to MAGIC or either of its runtimes requires a rebuild of Nostrand.

### Magic.Unity

An integration package to get MAGIC compiled Clojure code running in Unity games, including iOS builds.

It is a C# codebase hosted at https://github.com/nasser/Magic.Unity[nasser/Magic.Unity] and can be built with the `dotnet` command line tool. It includes bytecode post-processing to work around Unity specific issues with MAGIC compiled code.

`Magic.Unity` is not included in the pipeline because it can be import directly in unity via the manifest.json:

```
"sr.nas.magic.unity": "https://github.com/nasser/Magic.Unity.git"
```

## Requirements

* https://git-scm.com/[git]
* https://dotnet.microsoft.com/en-us/download[dotnet (version 7 or later)]
* https://www.mono-project.com/[mono]

## Usage

[source,bash]
----
git clone https://github.com/flybot-sg/new-magic
cd new-magic
dotnet build -t:CleanRepos
dotnet clean
dotnet build
----

This will clone MAGIC and its sub-projects locally, then build and bootstrap them in the correct order. The result should be the following folders corresponding to the sub-projects:

* `clojure.runtime`
* `magic.runtime`
* `magic`
* `nostrand`

A usable Nostrand executable should be available at `nostrand/bin/x64/Release/net471/NostrandMain.exe` which can be used with mono to run tasks and compile Clojure code to optimized DLL files.

You can use `nos` by adding to your path: `.../new-magic/nostrand/bin/Release/net471`

To verify that everything is setup properly, you can run:

```
nos version
;=>
Nostrand 1.0.0+e6ab32d3
Clojure.Runtime 1.10.0.0+3bd47b31
Magic.Runtime 1.0.0+33e9131a
Clojure 1.10.0-master-SNAPSHOT
```

## Legal

Copyright © 2015-2022 Ramsey Nasser and contributors

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.